[package]
name = "dfpp"
version = "0.0.1"
edition = "2021"
publish = false

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
flowistry = { git = "https://github.com/willcrichton/flowistry", rev = "1f469a4cce9f2e240ad14b5145669a8011d4e6b2" }
rustc_plugin = { git = "https://github.com/willcrichton/flowistry", rev = "1f469a4cce9f2e240ad14b5145669a8011d4e6b2" }
clap = { version = "3", features = ["derive", "cargo"] }
serde = { version = "1", features = ["derive"] }
lazy_static = "1"
ordermap = "0.3"
trait_enum = "0.5"
pretty = "0.11"
nom = "7"
log = "0.4"
simple_logger = "2"

# This is just for pinning this dependency
camino = "= 1.0.9"

[[bin]]
name = "cargo-dfpp"

[[bin]]
name = "dfpp"