[package]
name = "dfpp"
version = "0.0.1"
edition = "2021"
publish = false

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
#flowistry = { git = "https://github.com/willcrichton/flowistry", rev = "1f469a4cce9f2e240ad14b5145669a8011d4e6b2" }
#flowistry = { path = "../flowistry/crates/flowistry" }
flowistry = { git = "https://github.com/brownsys/flowistry", rev = "1e8e54beccb4720d713cf2baa5b205700f5987d6" }

#rustc_plugin = { git = "https://github.com/willcrichton/flowistry", rev = "1f469a4cce9f2e240ad14b5145669a8011d4e6b2" }
#rustc_plugin = { path = "../flowistry/crates/rustc_plugin" }
rustc_plugin = { git = "https://github.com/brownsys/flowistry", rev = "1e8e54beccb4720d713cf2baa5b205700f5987d6" }

clap = { version = "3", features = ["derive", "cargo", "env"] }
serde = { version = "1", features = ["derive"] }
lazy_static = "1"
ordermap = "0.3"
trait_enum = "0.5"
pretty = "0.11"
nom = "7"
log = "0.4"
simple_logger = "2"

#dot = "0.1"
dot = { git = "https://github.com/JustusAdam/dot-rust", rev = "ff2b42ceda98c639c8ea3cbfc56b83d6e06e8106"}
#dot = {path = "../../clones/dot-rust" }

serde_json = "1"
serde_path_to_error = "0.1"

# This is just for pinning this dependency
camino = "= 1.0.9"

[[bin]]
name = "cargo-dfpp"

[[bin]]
name = "dfpp"

