[workspace]
members = ["crates/*"]
exclude = [
    "props",
    "crates/paralegal-flow/tests",
    "crates/paralegal-policy/tests",
    "crates/paralegal-explore",
]
resolver = "2"

[workspace.dependencies]
indexical = "0.3.1"
serde = "1.0.188"
petgraph = { version = "0.6", features = ["serde-1"] }
strum = { version = "0.25", features = ["derive"] }
rustc_utils = { version = "=0.7.4-nightly-2023-08-25", features = [
    "indexical",
] }

[profile.release]
debug = true

#[replace]
#"rustc_utils:0.6.0-nightly-2023-04-12" = { git = "https://github.com/JustusAdam/rustc_plugin", rev = "80d92411810c709522119407be24745555adc87a" }
#"rustc_plugin:0.6.0-nightly-2023-04-12" = { git = "https://github.com/JustusAdam/rustc_plugin", rev = "80d92411810c709522119407be24745555adc87a" }
