[workspace]
members = ["crates/*"]
exclude = [
    "props",
    "crates/paralegal-flow/tests",
    "crates/paralegal-policy/tests",
    "crates/paralegal-explore",
]
resolver = "2"

[workspace.dependencies]
indexical = "0.3.1"
serde = "1.0.188"
petgraph = { version = "0.6", features = ["serde-1"] }
strum = { version = "0.25", features = ["derive"] }
# rustc_utils = { version = "=0.7.4-nightly-2023-08-25", features = [
#     "indexical",
# ] }
# rustc_plugin = "=0.7.4-nightly-2023-08-25"
rustc_utils = { git = "https://github.com/JustusAdam/rustc_plugin", rev = "89bc7b4979c8513a097068626b90b5b0e57f4917", features = [
    "indexical",
] }
rustc_plugin = { git = "https://github.com/JustusAdam/rustc_plugin", rev = "89bc7b4979c8513a097068626b90b5b0e57f4917" }
# rustc_plugin = { path = "../rustc_plugin/crates/rustc_plugin" }
# rustc_utils = { path = "../rustc_plugin/crates/rustc_utils" }

[profile.release]
debug = true

# [replace]
# "rustc_utils:0.7.4-nightly-2023-08-25" = { path = "../rustc_plugin/crates/rustc_utils" }
# "rustc_plugin:0.7.4-nightly-2023-08-25" = { path = "../rustc_plugin/crates/rustc_plugin" }
