[package]
name = "dfpp"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
flowistry = { version = "0.5.23", path = "../flowistry/crates/flowistry"}
rustc_plugin = { versio = "0.5.23", path = "../flowistry/crates/rustc_plugin"}
clap = { version = "3", features = ["derive"] }
serde = { version = "1", features = ["derive"] }

[[bin]]
name = "cargo-dfpp"

[[bin]]
name = "dfpp"