[workspace]
members = ["crates/*"]
exclude = [
    "props",
    "crates/paralegal-flow/tests",
    "crates/paralegal-policy/tests",
    "crates/paralegal-explore",
]
resolver = "2"

[workspace.dependencies]
indexical = "0.3.1"
serde = "1.0.188"
petgraph = { version = "0.6", features = ["serde-1"] }
strum = { version = "0.25", features = ["derive"] }
anyhow = { version = "1.0.72", features = ["backtrace"] }

rustc_utils = { version = "=0.7.4-nightly-2023-08-25", features = [
    "indexical",
] }
rustc_plugin = "=0.7.4-nightly-2023-08-25"
#flowistry = { path = "../flowistry/crates/flowistry", default-features = false }
flowistry = { git = "https://github.com/brownsys/flowistry", rev = "f4f837ee9f416e469d5a059f208c1dbf16481947", default-features = false }

[profile.release]
debug = true

[replace]
# "rustc_utils:0.7.4-nightly-2023-08-25" = { path = "../rustc_plugin/crates/rustc_utils" }
# "rustc_plugin:0.7.4-nightly-2023-08-25" = { path = "../rustc_plugin/crates/rustc_plugin" }

"rustc_utils:0.7.4-nightly-2023-08-25" = { git = "https://github.com/JustusAdam/rustc_plugin", rev = "dfcce83759b46ecd585d9d56e5c8e8d0b3df5b3c", features = [
    "indexical",
] }
"rustc_plugin:0.7.4-nightly-2023-08-25" = { git = "https://github.com/JustusAdam/rustc_plugin", rev = "dfcce83759b46ecd585d9d56e5c8e8d0b3df5b3c" }

# "rustc_utils:0.7.4-nightly-2023-08-25" = { git = "https://github.com/JustusAdam/rustc_plugin", rev = "e990ded60afc928f76293fb9ad265c58405da1a7", features = [
#     "indexical",
# ] }
# "rustc_plugin:0.7.4-nightly-2023-08-25" = { git = "https://github.com/JustusAdam/rustc_plugin", rev = "e990ded60afc928f76293fb9ad265c58405da1a7" }
