[package]
name = "lemmy"
version = "0.1.0"
edition = "2021"

[dependencies]
paralegal-policy = { path = "../../crates/paralegal-policy" }
anyhow = "1"
clap = { version = "=4.4", features = ["derive"] }
humantime = "2.1.0"
