name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo doc --document-private-items
    - name: Zip
      run: cd target/doc && tar -zcf github-pages * && mv github-pages ../..
    - uses: actions/upload-pages-artifact@main
    - uses: actions/deploy-pages@v1
    
      
